-- MySQL Script generated by MySQL Workbench
-- Sun Nov  1 10:36:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FootBall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Arbitre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Arbitre` ;

CREATE TABLE IF NOT EXISTS `Arbitre` (
  `id_arb` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_arb` VARCHAR(45) NOT NULL,
  `niveau` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_arb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compétition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compétition` ;

CREATE TABLE IF NOT EXISTS `Compétition` (
  `id_comp` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_comp` VARCHAR(45) NOT NULL,
  `manager` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_comp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Equipe` ;

CREATE TABLE IF NOT EXISTS `Equipe` (
  `num_equipe` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_equipe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`num_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Joueur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Joueur` ;

CREATE TABLE IF NOT EXISTS `Joueur` (
  `id_jou` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_jou` VARCHAR(45) NOT NULL,
  `prenom_jou` VARCHAR(45) NULL,
  `niveau` VARCHAR(45) NOT NULL,
  `num_maillo` INT NOT NULL,
  `age` INT NOT NULL,
  `taille` FLOAT NOT NULL,
  `Equipe_num_equipe` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_jou`, `Equipe_num_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Match` ;

CREATE TABLE IF NOT EXISTS `Match` (
  `id_match` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_equipe1` VARCHAR(45) NOT NULL,
  `nom_equipe2` VARCHAR(45) NOT NULL,
  `arbitre_principal` VARCHAR(45) NOT NULL,
  `resultat` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `tour` VARCHAR(45) NOT NULL,
  `Arbitre_id_arb` INT UNSIGNED NOT NULL,
  `Compétition_id_comp` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_match`, `Compétition_id_comp`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Match_has_Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Match_has_Equipe` ;

CREATE TABLE IF NOT EXISTS `Match_has_Equipe` (
  `Match_id_match` INT UNSIGNED NOT NULL,
  `Equipe_num_equipe` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Match_id_match`, `Equipe_num_equipe`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Organisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Organisateur` ;

CREATE TABLE IF NOT EXISTS `Organisateur` (
  `id_org` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom_org` VARCHAR(45) NOT NULL,
  `Joueur_id_jou` INT UNSIGNED NOT NULL,
  `Joueur_Equipe_num_equipe` INT UNSIGNED NOT NULL,
  `Arbitre_id_arb` INT UNSIGNED NOT NULL,
  `Equipe_num_equipe` INT UNSIGNED NOT NULL,
  `Stade_id_stade` INT UNSIGNED NOT NULL,
  `Visiteur_id_visit` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_org`, `Joueur_id_jou`, `Joueur_Equipe_num_equipe`, `Arbitre_id_arb`, `Equipe_num_equipe`, `Stade_id_stade`, `Visiteur_id_visit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Stade` ;

CREATE TABLE IF NOT EXISTS `Stade` (
  `id_stade` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `localisation` VARCHAR(45) NOT NULL,
  `nom_stade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_stade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Visiteur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Visiteur` ;

CREATE TABLE IF NOT EXISTS `Visiteur` (
  `id_visit` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_visit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `création`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `création` ;

CREATE TABLE IF NOT EXISTS `création` (
  `Compétition_id_comp` INT UNSIGNED NOT NULL,
  `Organisateur_id_org` INT UNSIGNED NOT NULL,
  `date_debut` DATE NOT NULL,
  `date_fin` DATE NOT NULL,
  PRIMARY KEY (`Compétition_id_comp`, `Organisateur_id_org`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
